services:
  - type: web
    name: learning-log
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn learning_log.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: learning_log.settings
      - key: PYTHON_VERSION
        value: 3.11
